"""empty message

Revision ID: 66c7fa468064
Revises: 
Create Date: 2018-04-18 13:41:54.047696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c7fa468064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('uID', sa.Integer(), nullable=False),
    sa.Column('vID', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uID', 'vID')
    )
    op.drop_table('likes')
    op.drop_constraint('has_vID_fkey', 'has', type_='foreignkey')
    op.drop_constraint('has_cName_fkey', 'has', type_='foreignkey')
    op.drop_constraint('review_vID_fkey', 'review', type_='foreignkey')
    op.add_column('vendor', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'name')
    op.create_foreign_key('review_vID_fkey', 'review', 'vendor', ['vID'], ['vID'])
    op.create_foreign_key('has_cName_fkey', 'has', 'category', ['cName'], ['cName'])
    op.create_foreign_key('has_vID_fkey', 'has', 'vendor', ['vID'], ['vID'])
    op.create_table('likes',
    sa.Column('uID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uID'], ['person.uID'], name='likes_uID_fkey'),
    sa.ForeignKeyConstraint(['vID'], ['vendor.vID'], name='likes_vID_fkey'),
    sa.PrimaryKeyConstraint('uID', 'vID', name='likes_pkey')
    )
    op.drop_table('like')
    # ### end Alembic commands ###
